#!/usr/bin/env python3

# Send messages to a matrix room with this python matrix client
# For example to be used in combination with rsync backup
# Author: Eelke Smit
# Email: mail [at] sjemm {dot} net
# Please use/share/comment/reference
# Date: 18-07-2017

# Usage: run this script with arguments
# Example: ./notify-matrix "This is my message for you"

# Requirements: python3 matrix module needed
# Example: pip3 install matrix_client

import sys
from matrix_client.client import MatrixClient

# Fill in your own matrix server url here
client = MatrixClient("https://yourserver.domain")

# Use an Existing user
# Fill in your own matrix username and password here
token = client.login_with_password(username="youruser", password="yourpassword")

# Join an existing matrix room (fill in yours here)
room = client.join_room("#yourroom:yourserver.domain")

# Send the argument given in bash to the room
# Example ./notify-matrix "This is my message for you"
room.send_text(sys.argv[1])
